export const events = [
  {
    title: "React Summit 2026",
    image: "/images/event1.png",
    slug: "react-summit-2026",
    location: "Amsterdam, Netherlands",
    date: "June 14, 2026",
    time: "9:00 AM",
  },
  {
    title: "GitHub Universe",
    image: "/images/event2.png",
    slug: "github-universe",
    location: "San Francisco, CA",
    date: "November 10, 2026",
    time: "10:00 AM",
  },
  {
    title: "JSConf Europe",
    image: "/images/event3.png",
    slug: "jsconf-europe",
    location: "Berlin, Germany",
    date: "May 28, 2026",
    time: "9:30 AM",
  },
  {
    title: "NodeConf Remote",
    image: "/images/event4.png",
    slug: "nodeconf-remote",
    location: "Online",
    date: "April 15, 2026",
    time: "2:00 PM",
  },
  {
    title: "WebAssembly Summit",
    image: "/images/event5.png",
    slug: "webassembly-summit",
    location: "Mountain View, CA",
    date: "August 22, 2026",
    time: "8:00 AM",
  },
  {
    title: "DevOps Days",
    image: "/images/event6.png",
    slug: "devops-days",
    location: "Austin, TX",
    date: "September 18, 2026",
    time: "9:00 AM",
  },
];
